# Generated by Django 3.2.9 on 2022-05-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='barn',
            field=models.BooleanField(default=True),
        ),
    ]
