# Generated by Django 3.2.9 on 2022-07-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_blogs_barn'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='reviwed',
            field=models.BooleanField(default=False),
        ),
    ]
