# Generated by Django 3.2.9 on 2022-09-08 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_framework_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='framework',
            options={'managed': True, 'verbose_name': 'FrameWork', 'verbose_name_plural': 'FrameWork'},
        ),
        migrations.AlterModelTable(
            name='framework',
            table='FrameWork',
        ),
    ]
