# Generated by Django 3.2.9 on 2022-09-08 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_auto_20220908_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'managed': True, 'verbose_name': 'BlogCategory', 'verbose_name_plural': 'BlogCategory'},
        ),
        migrations.AlterModelOptions(
            name='blogs',
            options={'managed': True, 'verbose_name': 'Blogs', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'managed': True, 'verbose_name': 'Comments', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='likes',
            options={'managed': True, 'verbose_name': 'Likes', 'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterModelTable(
            name='blogcategory',
            table='BlogCategory',
        ),
        migrations.AlterModelTable(
            name='blogs',
            table='Blogs',
        ),
        migrations.AlterModelTable(
            name='comments',
            table='Comments',
        ),
        migrations.AlterModelTable(
            name='likes',
            table='Likes',
        ),
    ]
