# Generated by Django 3.2.9 on 2022-09-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20220908_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='road_map',
            field=models.TextField(default='Add a perfect road map'),
        ),
    ]
