# Generated by Django 3.2.9 on 2022-09-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_auto_20220908_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='article',
            field=models.TextField(blank=True, null=True),
        ),
    ]
