# Generated by Django 3.2.9 on 2022-09-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_auto_20220909_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='stacks',
            field=models.ManyToManyField(blank=True, related_name='stacks', to='Blog.BlogCategory'),
        ),
    ]
