# Generated by Django 3.2.9 on 2022-09-09 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_alter_language_stacks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='framework',
            old_name='category',
            new_name='language',
        ),
    ]
