# Generated by Django 3.2.9 on 2022-09-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0015_framework_dev'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='stack',
            field=models.ManyToManyField(blank=True, related_name='stack', to='Blog.BlogCategory'),
        ),
        migrations.AlterField(
            model_name='framework',
            name='dev',
            field=models.CharField(blank=True, choices=[('Front-End', 'Front-End'), ('Back-End', 'Back-End')], max_length=40, null=True),
        ),
    ]
