# Generated by Django 3.2.9 on 2022-09-11 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_auto_20220911_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framework',
            name='road_map',
        ),
        migrations.CreateModel(
            name='RoadMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_map', models.TextField(default='Add a perfect road map')),
                ('add_links', models.CharField(max_length=100)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.language')),
            ],
            options={
                'verbose_name': 'RoadMap',
                'verbose_name_plural': 'RoadMap',
                'db_table': 'RoadMap',
                'managed': True,
            },
        ),
    ]
