# Generated by Django 3.2.9 on 2022-09-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0018_alter_roadmap_framework'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='road_map',
            field=models.TextField(default='Add a perfect road map'),
        ),
    ]
